[workspace]

members = [
    "lox",
    "lox-bytecode",
    "lox-compiler",
    "lox-vm",
    "lox-syntax",
    "lox-std",
    "lox-gc",
    "lox-mmap"
]

# For flamegraph
[profile.release]
debug = true
lto = true
