[package]
name = "lox-vm"
version = "0.1.0"
authors = ["Tim Peters <tim@darksecond.nl>"]
edition = "2021"

[dependencies]
lox-bytecode = { path = "../lox-bytecode" }
lox-gc = { path = "../lox-gc" }
arrayvec = "0.7.2"
